spring:
  datasource:
    url: jdbc:postgresql://dpg-d10ic8ripnbc738ruld0-a.oregon-postgres.render.com/trashpoint_db
    username: trashpoint_db_user
    password: UlmlVawVyYcGNSOuYEma0B20fVJlx0cH
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
