spring:
  datasource:
    url: jdbc:postgresql://dpg-c8i6zirph6e738ru1dp-a.oregon-postgres.render.com:5432/trashpoint_db
    username: trashpoint_db_user
    password: UlmlVawVyYcGNSOuYEma0B20fVJlx0cH
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
